{
 "title": "Marine Classifier Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "HTTP Requests for triton_predict",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "irate(http_requests_total{endpoint=\"/api/v1/triton_predict\"}[$__range])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Triton Success Inf Req ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(nv_inference_request_success[1m])",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Triton Failed Inf Req ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "irate(nv_inference_request_failure[1m])",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Total Model Load Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "marine_classifier_model_load_seconds",
     "legendFormat": "Total Model Load Time"
    }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "barchart",
   "description": "What’s the HTTP request duration that’s faster than 95% of requests over the last 24 hours?",
   "gridPos": { "h": 10, "w": 8, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum(rate(http_request_duration_seconds_bucket{endpoint=~\"/api/v1/predict|/api/v1/smart_predict|/api/v1/triton_predict\"}[3h])) by (le, endpoint)\r\n)\r\n",
     "legendFormat": "p95 {{endpoint}}"
    }
   ]
  },
  {
   "title": "LOGS",
   "type": "logs",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"\\\\\\\"marine-service\\\\\\\"\"} |= `result_class_name` | json result_class_name=\"result_class_name\"",
     "legendFormat": "{{result_class_name}}"
    }
   ]
  },
  {
   "title": "Inference Requests per model",
   "type": "stat",
   "description": "How many inference requests have been processed by the system, broken down by model name and whether they succeeded or failed",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(inference_requests_total) by (model_name, status)",
     "legendFormat": "{{model_name}}"
    }
   ]
  }
 ]
}