scrape_configs:
  - job_name: 'triton'
    static_configs:
      - targets: ['triton_cpu:8002']
  - job_name: "fluent-bit"
    metrics_path: "/api/v1/metrics/prometheus"
    static_configs:
      - targets: ["fluent-bit:2020"]
    fallback_scrape_protocol: "PrometheusText0.0.4"
