apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: oi-ai-mleng-takehome
  labels:
    grafana_datasource: "1"
data:
  datasources.yaml: |
    apiVersion: 1

    datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service:9090
        isDefault: true

      - name: loki
        type: loki
        access: proxy
        url: http://loki-service:3100
        jsonData:
          maxLines: 1000
