apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: oi-ai-mleng-takehome
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: prod-loki:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3100
              name: web
          args:
            - "-config.file=/etc/loki/loki-config.yaml"
          volumeMounts:
            - name: loki-config-volume
              mountPath: /etc/loki/loki-config.yaml
              subPath: loki-config.yaml
      volumes:
        - name: loki-config-volume
          configMap:
            name: loki-config
