apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: oi-ai-mleng-takehome
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'triton'
        static_configs:
          - targets: ['triton-service:8002']

      - job_name: "fluent-bit"
        metrics_path: "/api/v1/metrics/prometheus"
        static_configs:
          - targets: ["fluent-bit-service:2020"]
        fallback_scrape_protocol: "PrometheusText0.0.4"

      - job_name: 'marine-image-classifier'
        metrics_path: /metrics
        static_configs:
          - targets: ['marine-classifier-api-service:29000']

      - job_name: 'otel-collector'
        static_configs:
          - targets: ['otel-collector-service:9091']
