name: OI.AI.MLENG.TAKEHOME

services:
  maestro:
    build:
      context: ..
      dockerfile: docker/demo-maestro.Dockerfile
    container_name: maestro
    ports:
      - "8089:8089"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /c/Users/Gabriel/.kube:/home/vscode/.kube:ro
