global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'triton'
    static_configs:
      - targets: ['triton_cpu:8002']
  - job_name: "fluent-bit"
    metrics_path: "/api/v1/metrics/prometheus"
    static_configs:
      - targets: ["fluent-bit:2020"]
    fallback_scrape_protocol: "PrometheusText0.0.4"
  - job_name: 'marine-image-classifier'
    metrics_path: /metrics
    static_configs:
      - targets: ['marine_classifier:29000']
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:9090']
