name: CI Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Cache Poetry virtualenv
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pypoetry/virtualenvs
          ~/.cache/pip
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Cache Poetry installer
      uses: actions/cache@v4
      with:
        path: ~/.cache/pypoetry/installer
        key: ${{ runner.os }}-poetry-installer-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-installer-

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo 'export PATH="$HOME/.local/bin:$PATH"' >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        poetry install

    - name: Lint with Ruff
      run: |
        poetry run ruff check .

    - name: Check formatting with Black
      run: |
        poetry run black --check .

    - name: Sort imports with isort
      run: |
        poetry run isort --check .

    - name: Run tests with coverage and generate reports
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        poetry run pytest \
          --junitxml=tests/reports/pytest-report.xml \
          --cov=app \
          --cov-report=xml:tests/reports/coverage.xml \
          --cov-report=html:tests/reports/htmlcov \
          --cov-report=term

    - name: Upload pytest report artifact
      uses: actions/upload-artifact@v4
      with:
        name: pytest-report
        path: tests/reports/pytest-report.xml

    - name: Upload coverage report artifact (HTML)
      uses: actions/upload-artifact@v4
      with:
        name: coverage-html-report
        path: tests/reports/htmlcov/
